### ISSUE TITLE
Add WMT Verification into build

### ISSUE THREAD

**Issue by Samueldriessen** [distilagency/koval#11]
WMT verification achieved via HTML requires the string 

`google-site-verification: google87cf63255d10c540.html`

 available on the url www.example.com/google87cf63255d10c540.html

We have previously done this via proxy. Can also be done via HTML file upload.

**Comment by samlogan** [comment]
@Samueldriessen are you happy to use the solution I raised on Slack where you drop this file into the static folder via GitHub?

**Comment by Samueldriessen** [comment]
Hi Sam, happy to this. Is it possible to add this to the base build/repo - as this is the same file each time. Or does it need to be added individually per instance?

**Comment by samlogan** [comment]
Cheers @Samueldriessen, based on Koval being open source it's better for us to do this as part of the pre-launch checklist, I can add it to the current checklist
