### ISSUE TITLE
RSS Feed 

### ISSUE THREAD

**Issue by chungeric** [distilagency/koval#5]
Add the below code to netlify.toml

```
[[redirects]]
  from = "/feed"
  to = "<WORDPRESS_URL>/feed/"
  status = 200
  force = true
```

- Need to find a way to change the WordPress URL in the RSS feed, to the frontend URL

**Comment by chungeric** [comment]
Added as a commented template, but still need to figure out how to change the WordPress URLs in the actual RSS Feed.

**Comment by chungeric** [comment]
RSS feed is now configured in gatsby-config.js using the gatsby-plugin-feed plugin.

Example of RSS Feed here: https://www.capital-partners.com.au/rss.xml

**Comment by samlogan** [comment]
Nice work @chungeric
