### ISSUE TITLE
Add a build status in WordPress Admin area

### ISSUE THREAD

**Issue by chungeric** [distilagency/koval#6]
Netlify build status labels:
- Show a green label "Pushlished" when the site is finished building
- Red label 'Failed' when the build has failed
- Yellow label 'Building' when the site is building

**Comment by samlogan** [comment]
See here: https://github.com/distilagency/koval/issues/7

**Comment by chungeric** [comment]
Build status badge has been added in Netlify Connect. https://github.com/distilagency/netlify-connect/blob/master/includes/class-lbn-staging-status.php

I remember @markmollart suggested using the Netlify site ID rather than the deploy status url as it was easier to find for new developers for example. But this way, if the deploy status badge url structure changes it won't break the plugin and we can just update the badge url. Thoughts?
