### ISSUE TITLE
Add Rebuild Site button

### ISSUE THREAD

**Issue by chungeric** [distilagency/koval#7]
Add a 'Rebuild Site' button, to trigger a Netlify webhook to rebuild site.

**Comment by samlogan** [comment]
@chungeric and @markmollart can you guys catch up tomorrow on Slack about this, work out a good solution merging the implementation in the leaner-wordpress branch and the rebuild.php script on GA Perry? I would like to continue exploring how we fetch the build status in real time, possibly by querying the content-disposition header when making a get request to the badge URL on a set interval

![Screen Shot 2019-05-02 at 9 44 29 am](https://user-images.githubusercontent.com/8562933/57203478-bf603480-6ff3-11e9-8529-bbb0d2a35b58.jpg)

**Comment by chungeric** [comment]
This was added in the Netlify Connect plugin. https://github.com/distilagency/netlify-connect/blob/master/includes/class-lbn-status-badge.php
